replicaCount: 10

imagePullSecrets:
  - name: ghcr-creds

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

container:
    image: ghcr.io/dangrondahl/hello-go-app
    tag: ""
    port: 8080
    pullPolicy: Always

service:
  type: LoadBalancer
  port: 8082

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
