apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-fail-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "--fail"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#gitops-alerts\", \"username\": \"Mrs. Deploy\", \"text\": \"App Sync failed :fire:\", \"icon_emoji\": \":older_woman:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2