apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command: ["/bin/sh", "-c"] 
        args:
          - "curl --fail -X POST --data-urlencode 'payload={\"channel\": \"#gitops-alerts\", \"username\": \"Mrs. Deploy\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":older_woman:\"}' $SLACK_URL"
        env: 
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slack_hook
      restartPolicy: Never
  backoffLimit: 2